server:
  port: 0

spring:
  application:
    name: service-card
  rabbitmq:
    host: ${RABBIT_HOST:localhsot}
    port: 5672
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  datasource:
    url: jdbc:h2:mem:card-db
    driverClassName: org.h2.Driver
    username: sa
    password:
    hikari:
      maximumPoolSize: 10
    jpa:
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.H2Dialect

eureka:
  client:
    service-url:
      defaultZone: http://${USER_EUREKA}:${PASSWORD_EUREKA}@${EUREKA_SERVER:localhost}:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

mq:
  queues:
    novo-cartao-solicitado: novo-cartao-solicitado
